window.EXPANDED_REDDIT_COMMUNITIES = [
  {
    "name": "r/LocalLLaMA",
    "url": "https://www.reddit.com/r/LocalLLaMA/",
    "product": "本地 LLM、开源模型与推理工具",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "高；模型发布、量化/推理、硬件配置、基准测试与故障排查讨论持续出现，技术帖有较深评论链。",
    "atmosphere": "技术密度高、重实测和可复现性；对闭源营销、空泛结论、AI 生成灌水和伪装软广较敏感。",
    "sentiment": "对真正开放、可本地运行且有数据支撑的项目积极；对夸张宣传和只贴链接的商业项目明显负面。",
    "main_topics": [
      "开源大模型发布与评测",
      "量化、推理后端与显存优化",
      "GPU/本地硬件配置",
      "微调、RAG 与本地部署",
      "模型基准、隐私与离线使用"
    ],
    "relevance": "高：适合验证 Buildin AI 的本地模型接入、开发者工作流、可观测性与自动化能力，但必须提供技术细节。",
    "notes": "官方搜索摘要明确给出自推广约 1/10 的指导；社区近期也有成员公开抱怨低质内容和无耻自推。成员数因未能在检查时稳定读取 Reddit 页面而不填。",
    "tier": "P0",
    "category": "AI 开发者 / 开源 LLM",
    "posting_pattern": "发布/评测帖、实测对比、配置求助和项目复盘为主；标题通常直接写模型、参数、硬件或结果，代码、仓库、表格和复现实验更易获得讨论。",
    "user_profile": "本地推理玩家、ML/LLM 工程师、开源维护者、硬件发烧友及重视隐私的高级用户。",
    "moderation": "严格",
    "promo_ratio": "观察估计：5%–12%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据搜索可见帖子与社区规则摘要：工具/模型自荐可见，但规则以 1/10 为指导，且社区对软广与低质自推有明显反感；比例指可辨识推广/自荐帖在普通信息流中的大致可见占比。",
    "promo_strategy": "先持续参与技术讨论；用“问题—方法—环境—结果—限制”的工程复盘发布，提供公开仓库、配置、基准或可复现 demo；透明披露作者关系，把 Buildin AI 放在解决方案上下文而非标题式广告中。",
    "risk": "闭源 SaaS 直链、无 benchmark 的“革命性”口号、隐藏商业关系、跨社区复制文案或 AI 味明显的长文，容易被删、被质疑或遭集中差评。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/ChatGPT",
    "url": "https://www.reddit.com/r/ChatGPT/",
    "product": "ChatGPT 与大众生成式 AI",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "极高；内容更新快，产品体验、截图、提示词、新闻、故障、创意玩法和梗图并存。",
    "atmosphere": "大众化、娱乐性强、热点驱动；技术深度差异大，注意力竞争激烈，直白推广易被视作噪声。",
    "sentiment": "对直观、惊喜感强的 ChatGPT 用例较积极；对重复问题、低努力内容和与 ChatGPT 关系弱的产品广告较负面。",
    "main_topics": [
      "ChatGPT 功能与版本体验",
      "提示词与创意用法",
      "生成内容展示",
      "产品故障、限制与订阅体验",
      "AI 新闻、伦理与社会影响"
    ],
    "relevance": "中高：覆盖面大，适合做认知曝光和直观 demo；但流量噪声高，未必带来高质量开发者线索。",
    "notes": "社区自述为讨论 ChatGPT 和 AI、且非 OpenAI 官方；搜索摘要显示自推广通常被引导到每周置顶推广串，低努力及“是否宕机”类帖子会被清理。成员数未稳定核验。",
    "tier": "P1",
    "category": "大众 AI / ChatGPT",
    "posting_pattern": "高频短帖、截图/视频 demo、体验吐槽、提问与热点新闻；视觉化、结果先行的内容比长篇产品介绍更容易获得互动。",
    "user_profile": "普通 ChatGPT 用户、内容创作者、学生、知识工作者、AI 爱好者，以及一部分开发者和工具创业者。",
    "moderation": "严格",
    "promo_ratio": "观察估计：3%–8%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据搜索结果中“推广进入每周自推广 mega thread”的规则摘要，以及主页/帖子搜索中推广内容相对少见；隐性软广可能未被识别。",
    "promo_strategy": "优先在允许的周度推广串中发布；常规内容用一张图或短视频展示具体结果，正文讲清问题与操作步骤，不在标题硬推品牌；评论中按需回答并透明披露关联。",
    "risk": "独立产品广告、与 ChatGPT 关联薄弱、只放落地页、夸张标题、低努力 AI 生成文案或绕过推广串，存在高删帖和负面评论风险。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/ClaudeAI",
    "url": "https://www.reddit.com/r/ClaudeAI/",
    "product": "Claude 与 Claude Code",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "高；Claude/Claude Code 使用体验、限额、编码工作流、CLAUDE.md、故障与版本变化讨论活跃。",
    "atmosphere": "偏实用和开发者导向，用户愿意分享具体工作流，也会快速放大服务波动、限额和行为退化等负面体验。",
    "sentiment": "对可复现的 Claude Code 提效案例和深入教程积极；对“只展示产品、不解释如何构建”的推广越来越不耐烦。",
    "main_topics": [
      "Claude 与 Claude Code 使用体验",
      "编程代理工作流",
      "CLAUDE.md 与上下文管理",
      "额度、性能和服务变化",
      "项目展示与构建方法"
    ],
    "relevance": "高：Buildin AI 若能展示 Claude/Claude Code 相关自动化、上下文编排或开发流程，受众匹配度高。",
    "notes": "社区自述明确聚焦 Claude 和 Claude Code；版主关于 Rule 7 的更新标题强调“更少垃圾、更重视你如何构建”，第三方规则摘要还显示账号年龄与 karma 门槛。成员数未稳定核验。",
    "tier": "P0",
    "category": "AI 编程 / Claude",
    "posting_pattern": "经验贴、问题排查、额度/版本讨论、代码代理成果展示；高价值帖子通常附步骤、提示词、配置、失败教训或可见 demo。",
    "user_profile": "Claude 付费用户、软件工程师、Claude Code 重度用户、AI 编程早期采用者和开发工具创始人。",
    "moderation": "严格",
    "promo_ratio": "观察估计：5%–10%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据规则更新对 spam/showcase 的收紧，以及搜索可见的项目展示模式；未对固定时间窗完整抓样，因此仅给区间。",
    "promo_strategy": "采用深度 build log：展示 Claude 参与了哪些步骤、架构/提示词/上下文设计、指标和失败点；提供无需注册即可看的 demo，先贡献评论并满足账号门槛，再透明提及 Buildin AI。",
    "risk": "新号直接发产品、只有成品截图没有构建过程、借 Claude 热点引流但关联弱、反复贴同一链接，可能触发 Rule 7、账号门槛或社区反感。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/AI_Agents",
    "url": "https://www.reddit.com/r/AI_Agents/",
    "product": "AI Agent、Agentic Workflow 与多智能体工具",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "高；框架、架构、工具调用、MCP、真实案例、项目发布与对 agent 概念的争论持续出现。",
    "atmosphere": "建设者和创业者密集、对新品较开放，但营销含量也高；用户要求看到 agent 真正运行，而非把普通聊天机器人包装成 agent。",
    "sentiment": "对有录像、公开仓库、无需注册 demo 和架构拆解的 agent 项目积极；对概念炒作和落地页导流持怀疑态度。",
    "main_topics": [
      "AI Agent 架构与框架",
      "工具调用、MCP 与编排",
      "多智能体系统",
      "Agent demo 与产品发布",
      "可靠性、评测和生产落地"
    ],
    "relevance": "很高：Buildin AI 的自动化/代理能力与社区主题直接重合，适合早期反馈、案例验证和开发者获客。",
    "notes": "官方社区摘要定义 agent 为可使用工具/执行函数的自治或半自治 LLM；搜索资料显示该社区容忍发布，但强调真实贡献、适度自推和技术内容。成员数未稳定核验。",
    "tier": "P0",
    "category": "AI Agent / 开发者工具",
    "posting_pattern": "架构讨论、观点贴、demo 视频、开源项目、失败复盘和“我构建了什么”；强观点标题可获高互动，但评论会追问技术真实性。",
    "user_profile": "Agent 工程师、AI 创业者、开源框架用户、自动化顾问、研究者与关注 agent 落地的产品人员。",
    "moderation": "中等",
    "promo_ratio": "观察估计：15%–25%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据搜索可见的 launch/showcase 友好度及建设者密度，产品自荐比通用 AI 社区更常见；区间包含明确项目发布和带产品导向的案例帖。",
    "promo_strategy": "直接展示 agent 执行闭环：短录屏、公开 repo 或免登录 demo；正文给出工具链、边界条件、失败案例和评测，明确“我是作者”；把 CTA 降到最低并持续参与他人帖子。",
    "risk": "把简单 chatbot 冒充 agent、注册墙挡住 demo、无技术细节、批量自动发帖或账号历史几乎全是推广，会被专业用户指出并可能被封控。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/artificial",
    "url": "https://www.reddit.com/r/artificial/",
    "product": "综合人工智能新闻、研究与产业讨论",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "高；AI 新闻、研究进展、产业观点、政策伦理与产品讨论并存，热点事件驱动明显。",
    "atmosphere": "综合型、观点分化大；对新闻与社会影响讨论开放，但对商业宣传、煽动性标题和低历史账号较警惕。",
    "sentiment": "对有公共价值、技术新意或行业意义的内容中性偏积极；对将产品发布包装成新闻的行为负面。",
    "main_topics": [
      "AI 新闻与产业动态",
      "研究进展与模型能力",
      "AI 政策、伦理和社会影响",
      "产品与应用案例",
      "通用人工智能观点讨论"
    ],
    "relevance": "中：适合有明确行业洞察、研究数据或社会议题的 Buildin AI 内容，不适合作为直接产品发布渠道。",
    "notes": "官方社区搜索摘要明确要求首个帖子或评论不能含推广，并给出 10% 自推广上限；同时保留对煽动、钓鱼和低历史账号的裁量权。成员数未稳定核验。",
    "tier": "P2",
    "category": "综合 AI / 新闻讨论",
    "posting_pattern": "外链新闻、研究解读、观点讨论和问题帖为主；内容需有 AI 相关性，争议话题评论量可高，但品牌帖难以自然融入。",
    "user_profile": "AI 爱好者、研究与工程从业者、科技新闻读者、政策伦理关注者及产业观察者。",
    "moderation": "严格",
    "promo_ratio": "观察估计：3%–8%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据官方摘要中的首帖禁推广与 10% 上限，以及第三方对产品发布过滤较强的描述；可见比例可能因删帖而低于投稿比例。",
    "promo_strategy": "先建立社区历史；发布原创数据、行业研究或技术方法论，产品只作为案例并披露关系；不要把发布稿伪装成新闻，优先无链接正文，必要链接放在有上下文的评论中。",
    "risk": "首个互动即推广、品牌新闻稿、诱导性标题、争议钓鱼、超过 10% 的自推历史，容易被移除或封禁；受众宽泛也可能导致转化弱。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/n8n",
    "url": "https://www.reddit.com/r/n8n/",
    "product": "n8n 工作流自动化",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "高；工作流搭建、节点配置、集成排障、模板、AI 自动化和自托管问题密集。",
    "atmosphere": "实操导向、技术支持氛围强，同时对不分享工作流细节的炫耀帖和借社区卖模板/服务较敏感。",
    "sentiment": "对可导入 workflow、逐节点说明和真实业务结果积极；对“Workflow Code Not Included”、付费墙和竞品式导流负面。",
    "main_topics": [
      "n8n 工作流设计与排障",
      "API、节点和第三方集成",
      "AI Agent 与 LLM 自动化",
      "自托管、性能与安全",
      "模板、案例和最佳实践"
    ],
    "relevance": "很高：与 Buildin AI 的自动化和 AI 工作流定位直接重合，可触达高意向实施者和技术买家。",
    "notes": "搜索结果可核验到 Weekly Self Promotion Thread、工作流展示帖，以及社区对“不附工作流代码”内容的公开讨论；另有新版规/标签/Automod 更新。成员数未稳定核验。",
    "tier": "P0",
    "category": "工作流自动化 / n8n",
    "posting_pattern": "求助帖、节点截图、JSON/workflow 分享、教程、案例复盘和周度推广串；可复制模板和完整配置通常比概念介绍更受欢迎。",
    "user_profile": "n8n 自托管用户、自动化工程师、技术型运营、咨询顾问、AI 工作流创始人及中小企业实施者。",
    "moderation": "严格",
    "promo_ratio": "观察估计：8%–15%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据周度自推广串和社区中可见的 workflow showcase，同时考虑新版规与对不附工作流内容的反感；比例指普通流中可辨识的推广/自荐，不含集中串全部评论。",
    "promo_strategy": "把 Buildin AI 具体接入 n8n 场景，提供可导入 JSON、节点图、凭据占位说明、成本/时延和失败处理；推广内容优先进入周度串，常规帖以教程或问题复盘为主并透明披露。",
    "risk": "不提供 workflow、只发演示视频或落地页、卖模板不说明、贬低 n8n 或发布闭源竞品直链，会被删帖、差评或视为搭便车。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/automation",
    "url": "https://www.reddit.com/r/automation/",
    "product": "通用自动化、AI 自动化与效率工具",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "中等；话题跨度大，从个人效率、业务流程到 ChatGPT/AI 自动化、RPA 和工具推荐。",
    "atmosphere": "泛自动化、问题解决导向，入门用户较多；因主题宽泛，工具推荐和推广容易混杂，内容质量不均。",
    "sentiment": "对能节省时间并清楚解释流程的案例积极；对自动群发、无人工审核和纯销售式工具帖谨慎。",
    "main_topics": [
      "业务流程自动化",
      "AI 与 ChatGPT 自动化",
      "个人效率与重复任务",
      "RPA、脚本和集成工具",
      "工具推荐与实施问题"
    ],
    "relevance": "中高：适合用具体业务场景验证 Buildin AI，但受众意图比 n8n/AI_Agents 更分散。",
    "notes": "官方社区摘要将 automation、ChatGPT 与自动化可能性并列；未检索到足够清晰的社区专属推广条款，因此严格度与比例主要基于可见内容和 Reddit 通用反垃圾规范，需发帖前再次核对实时规则。",
    "tier": "P1",
    "category": "通用自动化 / 效率",
    "posting_pattern": "“如何自动化某任务”、工具选择、流程展示和结果分享；清晰写出输入、触发器、步骤和节省时间的帖子更易得到回应。",
    "user_profile": "自动化爱好者、中小企业主、运营人员、RPA/集成开发者、效率工具用户和 AI 新手。",
    "moderation": "中等",
    "promo_ratio": "观察估计：10%–20%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据社区主题较宽、工具推荐自然出现，且未找到明确的专属推广禁令；区间不代表规则许可比例，发帖前必须复核侧栏与发帖提示。",
    "promo_strategy": "以“手工流程如何被自动化”为主线，附流程图、前后对比和可复制步骤；先在求助帖中提供完整答案，只有高度相关时再披露并提及 Buildin AI，避免自动发布。",
    "risk": "版规证据不足导致政策误判；泛化产品帖、批量自动发布、未经人工审核的回复、夸大节省效果或只贴链接，均可能被判为 spam。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/nocode",
    "url": "https://www.reddit.com/r/nocode/",
    "product": "No-code / Low-code 产品构建与自动化",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "中等；工具比较、搭建求助、产品展示、MVP、数据库/自动化组合及创业实践较常见。",
    "atmosphere": "对初学者和 maker 较友好，重视“用什么搭成、怎么搭”；社区较聚焦，低努力推广会显得突出。",
    "sentiment": "对真实构建故事、模板和诚恳求反馈积极；对伪装求反馈的销售帖和贬低 no-code 的内容负面。",
    "main_topics": [
      "无代码/低代码工具比较",
      "MVP 与应用搭建",
      "自动化与数据集成",
      "Bubble、Webflow、Airtable 等生态",
      "产品展示、反馈与 maker 经验"
    ],
    "relevance": "中高：Buildin AI 若面向非工程用户提供 AI 搭建或自动化，可获得早期产品反馈；规模和曝光可能有限。",
    "notes": "官方社区摘要定位为“不需要成为开发者也能构建酷东西”；第三方搜索摘要描述社区规模较小但参与度聚焦，并建议以真实 build 而非高频 launch board 方式参与。成员数未采用第三方近似值。",
    "tier": "P1",
    "category": "No-code / Maker",
    "posting_pattern": "工具选择问答、教程、搭建日志、MVP 展示和反馈请求；带具体栈、截图、模板和经验教训的内容更自然。",
    "user_profile": "非技术创始人、独立开发者、运营/增长人员、no-code 顾问、设计师和希望快速做 MVP 的业务用户。",
    "moderation": "中等",
    "promo_ratio": "观察估计：12%–22%",
    "promo_ratio_note": "观察估计，非严谨抽样。依据社区 maker/showcase 属性及搜索可见的工具内容；未获得完整实时 feed 或明确抽样窗口，区间包括产品展示、模板和带导流意图的求反馈帖。",
    "promo_strategy": "发布“如何用 Buildin AI 从需求到可运行 MVP”的分步案例，公开模板或演示，说明自己是作者并真诚征求特定反馈；先评论帮助其他 maker，再做低频发布。",
    "risk": "社区体量较小，重复曝光很显眼；伪装成用户提问、夸张收入故事、无上下文链接、频繁 cross-post 或攻击其他 no-code 工具会损害信誉。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/webdev",
    "url": "https://www.reddit.com/r/webdev/",
    "product": "前端、后端与 Web 工程实践",
    "members": null,
    "members_display": "未可靠核验",
    "activity": "极高；前后端框架、职业问题、调试、架构、性能、部署、工具和项目展示均有大量讨论。",
    "atmosphere": "成熟、技术务实、对营销极敏感；常规讨论欢迎深入经验，但项目展示和反馈有明确时段/版位限制。",
    "sentiment": "对扎实教程、可复现工程经验和真诚技术讨论积极；对商业推广、招揽业务、隐性内容营销和错时 showcase 明显负面。",
    "main_topics": [
      "前端与后端开发",
      "框架、语言和工程工具",
      "调试、性能与部署",
      "职业与团队实践",
      "Showoff Saturday 项目展示"
    ],
    "relevance": "中：开发者覆盖广，但 Buildin AI 只有在解决明确 Web 开发问题时才相关；直接获客受版规强限制。",
    "notes": "官方规则搜索摘要明确出现“No self-promotion”；多份 2026 规则摘要一致指出，非商业项目展示仅限 Showoff Saturday 且需讲技术细节。成员数因第三方数值冲突且无法直接核验而置空。",
    "tier": "P2",
    "category": "Web 开发 / 通用开发者",
    "posting_pattern": "技术问答、经验讨论、教程和职业话题；个人项目/作品集/求反馈集中到 Showoff Saturday，版式和 flair 要求明确。",
    "user_profile": "前端、后端、全栈工程师，学生与初级开发者，技术负责人、自由职业者和 Web 工具作者。",
    "moderation": "极严格",
    "promo_ratio": "观察估计：1%–5%（常规信息流）",
    "promo_ratio_note": "观察估计，非严谨抽样。依据官方“No self-promotion”规则与 Showoff Saturday 限定通道；该区间仅指常规信息流中仍可辨识的展示/推广内容，不把周六集中展示串整体计入。",
    "promo_strategy": "不要常规发产品推广；先以不带 CTA 的技术教程、开源实现或故障复盘贡献价值。仅在符合条件的 Showoff Saturday 展示非商业项目，突出技术细节；商业产品应考虑 Reddit Ads 或其他社区。",
    "risk": "商业推广和 solicitation 被明确禁止；在非周六求反馈、教程暗藏付费产品链接、评论区软广或账号专为引流，均有很高删帖/封禁风险。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/SaaS",
    "url": "https://www.reddit.com/r/SaaS/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "高：围绕 SaaS 获客、定价、MRR、产品反馈与创始人复盘持续有新讨论；热门帖与低互动推广帖并存。",
    "atmosphere": "创始人导向、务实但噪声偏高；真实指标、失败复盘和具体问题通常比泛泛成功学更受欢迎。",
    "sentiment": "中性偏正向：愿意交流增长经验，但对伪装成经验帖的广告、模板化 AI 内容和重复推广较警惕。",
    "main_topics": [
      "SaaS 获客与增长",
      "定价与变现",
      "MRR/ARR 复盘",
      "产品验证与反馈",
      "技术栈与运营工具",
      "独立创业"
    ],
    "relevance": "高：Buildin AI 可围绕 AI 建站、原型验证、内容生产和小团队提效切入，受众与 SaaS 创始人高度重合。",
    "notes": "公开检索显示社区对自推广采取条件式管理：产品提及应服务于故事、指标、挑战或具体问题，并避免重复投放；规则与允许入口可能变化，发布前必须复核置顶帖和侧栏。成员数来源冲突较大，故不写数值。",
    "tier": "P0",
    "category": "SaaS/创始人",
    "posting_pattern": "高频问答、里程碑/收入复盘、失败复盘、工具与渠道讨论；推广常包装为 build-in-public、案例拆解或反馈请求，纯链接帖生存率低。",
    "user_profile": "SaaS 创始人、独立开发者、早期增长人员、微型创业团队，以及寻找工具和同业经验的运营者。",
    "moderation": "严格",
    "promo_ratio": "观察估计：20%–35%",
    "promo_ratio_note": "观察估计，非严格抽样。依据公开搜索结果中大量产品发布、收入复盘、反馈请求及规则讨论的可见频率；其中包含软性产品露出，并不等于全部获版主认可或长期留存。",
    "promo_strategy": "先以可复用的实战复盘建立账号信誉，再在允许的周期/主题帖中透明披露与 Buildin AI 的关系。正文优先给出问题、过程、前后对比和真实指标，把链接放在规则允许的位置；避免重复发同一 URL。",
    "risk": "高：营销痕迹明显、重复域名、低信息量的“我做了一个 AI 工具”或无披露导流，容易被删帖、降权或被用户反感。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/SideProject",
    "url": "https://www.reddit.com/r/SideProject/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "高：项目展示与反馈请求更新快，视觉化 demo、新奇小工具和清晰故事更容易获得互动。",
    "atmosphere": "展示型、实验性、对创作者友好；容忍自我介绍和产品链接，但对只有落地页、没有上下文的投放兴趣有限。",
    "sentiment": "偏正向：用户乐于看新项目并给建议，但同类发布密集，注意力竞争强。",
    "main_topics": [
      "Side project 展示",
      "MVP 发布",
      "产品反馈",
      "独立开发",
      "设计与技术实现",
      "早期用户验证"
    ],
    "relevance": "高：适合展示 Buildin AI 制作出的真实网站、原型或模板，并收集首轮产品反馈。",
    "notes": "社区定位即分享 side project 并获得建设性反馈；公开页面样本显示“我做了什么+请反馈”是主流格式。第三方规则汇总也一致强调讲清动机、构建过程和具体反馈问题。",
    "tier": "P0",
    "category": "独立开发/项目展示",
    "posting_pattern": "以截图、短视频、可访问 demo、构建故事和“请 roast/给反馈”为主；新奇轻量项目可爆发，常规 SaaS 发布竞争激烈。",
    "user_profile": "独立开发者、设计师、学生开发者、周末创业者、早期创始人及愿意试用新产品的 maker。",
    "moderation": "宽松",
    "promo_ratio": "观察估计：45%–65%",
    "promo_ratio_note": "观察估计，非严格抽样。社区本身以分享作品为核心，公开新帖样本中相当部分直接展示自有项目；将“作品展示/求反馈”计入广义推广，因此区间高。",
    "promo_strategy": "用强视觉 demo 和具体使用场景开场，说明为何构建、用了什么方法、当前不足，并提出 2–3 个可回答的问题。透明表明创作者身份，积极回复评论；不要只贴首页链接。",
    "risk": "中：虽然容许展示，但同质化 AI 工具、夸张标题、无 demo 或跨社区重复文案容易被忽视、点踩或按垃圾内容处理。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Entrepreneur",
    "url": "https://www.reddit.com/r/Entrepreneur/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "很高：创业问答、经验故事、商业模式、销售和运营话题密集，评论量差异较大。",
    "atmosphere": "大众创业社区，经验与动机内容并存；用户对可执行建议、真实失败和经营数据更买账，对引流套路敏感。",
    "sentiment": "中性：互助意愿强，但对营销人员、咨询获客、DM 诱导和成功学叙事较怀疑。",
    "main_topics": [
      "创业经验",
      "销售与获客",
      "商业模式",
      "小团队运营",
      "融资与现金流",
      "失败教训"
    ],
    "relevance": "中高：覆盖面大，可触达需要快速上线网站和验证想法的创业者，但直接产品推广窗口窄。",
    "notes": "公开规则摘要显示主版面禁止销售、推广、招募、求职、融资招揽及导流，推广应进入指定周期帖；因此更适合品牌心智与需求研究，不适合冷启动硬广。",
    "tier": "P1",
    "category": "创业/经营",
    "posting_pattern": "问题求助、创业故事、收入/失败复盘、观点讨论与周期性业务分享帖；标题党和故事化内容多，评论区常出现工具推荐需求。",
    "user_profile": "创业者、准创业者、小企业经营者、销售/营销人员、服务商及寻求创业建议的人群。",
    "moderation": "极严格",
    "promo_ratio": "观察估计：5%–12%",
    "promo_ratio_note": "观察估计，非严格抽样。按主版面可见且带明显品牌/产品目的的内容估算；规则将直接推广导入指定周期帖，因此主 feed 明显推广占比较低，软性故事植入仍可能存在。",
    "promo_strategy": "主 feed 只发不依赖产品名也成立的深度经验或失败复盘；有自然相关性时再透明披露。直接介绍 Buildin AI 应优先使用当期官方推广线程，并先积累高质量评论记录。",
    "risk": "极高：链接、DM 引导、个人主页导流、招聘/销售式 CTA 或伪装案例均可能触发删除乃至永久封禁。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/startups",
    "url": "https://www.reddit.com/r/startups/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "高：围绕可规模化创业公司的问题、融资、联合创始人、验证与运营持续讨论，结构化主题帖活跃。",
    "atmosphere": "规则驱动、强调问题与解决方案；相比展示产品，更重视可泛化的创业经验和高质量讨论。",
    "sentiment": "中性偏审慎：对严肃创业问题较友好，对任何与自有产品、雇主或客户相关的隐性推广高度警惕。",
    "main_topics": [
      "创业问题与解决方案",
      "产品市场匹配",
      "融资",
      "联合创始人",
      "增长与运营",
      "用户反馈"
    ],
    "relevance": "中高：Buildin AI 与 MVP、验证、早期上线高度相关，但只能在合规主题帖或去品牌化经验分享中出现。",
    "notes": "社区公开说明聚焦“startup problems and solutions”。规则摘要表明直接销售、广告和自推广通常限于指定主题帖，反馈、调查、beta 招募也应进入相应 recurring thread；发帖格式和 flair 要求较细。",
    "tier": "P1",
    "category": "初创公司/创业",
    "posting_pattern": "结构化问答、融资/PMF/团队问题、经验复盘及周期性 Share Your Startup/Feedback 线程；独立产品发布在主 feed 的空间很小。",
    "user_profile": "科技创业者、早期员工、投资与加速器相关人士、产品/增长负责人，以及筹备创业的人群。",
    "moderation": "极严格",
    "promo_ratio": "观察估计：3%–10%",
    "promo_ratio_note": "观察估计，非严格抽样。依据公开规则将推广和反馈请求集中到指定线程、主版面强调问题解决；区间只描述主 feed 中可见的明显或软性推广，不含集中帖内评论。",
    "promo_strategy": "围绕“如何用 AI 建站更快验证需求”写可独立成立的方法论或复盘，不以产品为标题中心；直接链接和 beta 招募仅放入当期指定线程，严格遵循 flair、模板和账户门槛。",
    "risk": "极高：错用 flair、缺少规定模板、主版面产品发布、问卷/用户研究、导流或把创业旅程当博客推广，都可能被自动或人工移除。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/indiehackers",
    "url": "https://www.reddit.com/r/indiehackers/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中高：以 bootstrap、build-in-public、收入里程碑、获客和产品反馈为主，发帖量不及大型创业板块但受众更聚焦。",
    "atmosphere": "创作者友好、重透明和实战；社区愿意讨论自有产品，但对低质量批量推广和虚假指标反感。",
    "sentiment": "偏正向：对诚实分享过程、数字和失败较友好，对“先提供价值再提产品”的内容接受度高。",
    "main_topics": [
      "Bootstrap 创业",
      "Build in public",
      "MRR 里程碑",
      "获客渠道",
      "产品发布与反馈",
      "独立开发者工具"
    ],
    "relevance": "高：Buildin AI 与低成本构建、快速发布、个人创业和小团队工作流高度匹配。",
    "notes": "社区公开定位是通过构建产品 bootstrap 成功的人群。公开检索可见新版规讨论及推广合规讨论，说明社区正在提升内容质量；产品展示应以旅程、数据和学习为核心，而非纯广告。",
    "tier": "P0",
    "category": "独立创业/Bootstrap",
    "posting_pattern": "收入/里程碑更新、构建日志、获客实验、失败复盘、工具发布与反馈；评论更偏同行建议和经验交换。",
    "user_profile": "独立黑客、微型 SaaS 创始人、solo founder、开发者营销者及希望 bootstrap 的产品构建者。",
    "moderation": "中等",
    "promo_ratio": "观察估计：30%–50%",
    "promo_ratio_note": "观察估计，非严格抽样。广义上把 build-in-public、产品展示和收入复盘中的自有产品提及计为推广；公开内容显示此类帖子常见，但新版规趋向清理低价值自推。",
    "promo_strategy": "采用 build-in-public：展示从问题、原型到用户反馈的过程，提供真实数据或可复制步骤；用产品作为案例而不是唯一卖点，透明披露身份，并持续参与评论。",
    "risk": "中高：社区虽允许创始人内容，但规则趋严；一次性账号、虚构数据、AI 批量文案、重复发布和只留链接可能被删除或失去信任。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/ProductManagement",
    "url": "https://www.reddit.com/r/ProductManagement/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中高：围绕 PM 方法、职业、组织协作、roadmap、discovery 和指标的讨论稳定；职业问题集中到周期帖。",
    "atmosphere": "专业、方法论导向、对低努力内容容忍度低；更看重有背景、有取舍、有复盘的产品实践。",
    "sentiment": "中性偏严格：对高质量案例讨论友好，但对产品研究、问卷、招募和工具推广防范明显。",
    "main_topics": [
      "产品战略",
      "用户发现",
      "Roadmap 与优先级",
      "PM 职业发展",
      "跨团队协作",
      "指标与实验"
    ],
    "relevance": "中：可通过 AI 原型、需求验证、文档与协作案例建立认知，但不是直接获客或用户调研场。",
    "notes": "公开社区规则摘要明确：自推广受限；产品研究即使不自推通常也不允许；学术研究需预先批准；项目仅可在 Friday Show and Tell 等指定线程展示，职业问题进入季度线程。",
    "tier": "P1",
    "category": "产品管理/专业社区",
    "posting_pattern": "实践难题、框架争论、案例复盘、职业讨论和固定主题帖；工具发布、问卷和泛泛入门问题通常被分流或移除。",
    "user_profile": "产品经理、产品负责人、设计/研究/工程协作者、PM 求职者及产品管理领导者。",
    "moderation": "极严格",
    "promo_ratio": "观察估计：2%–8%",
    "promo_ratio_note": "观察估计，非严格抽样。规则对自推广、产品研究和 app feedback 均设窄入口，故主 feed 中明确推广预计很低；指定 Show and Tell 线程不计入主 feed 比例。",
    "promo_strategy": "优先贡献去品牌化的产品实践案例，例如 AI 原型如何改变 discovery 周期；若要展示 Buildin AI，只使用当期 Friday Show and Tell，并避免问卷、招募和“求用户研究”式发帖。",
    "risk": "极高：任何带研究招募、反馈收集、链接导流或伪装成工具讨论的推广都可能被移除；版主保留较强自由裁量权。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/smallbusiness",
    "url": "https://www.reddit.com/r/smallbusiness/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "很高：经营者持续提问获客、现金流、员工、定价、网站和本地运营问题，评论以实际经验为主。",
    "atmosphere": "问题解决型、务实、预算敏感；成员更关心结果、成本和实施难度，不欢迎供应商把社区当销售渠道。",
    "sentiment": "中性偏务实：对具体、节省成本的建议友好，对服务商和 SaaS 的隐性推销警惕。",
    "main_topics": [
      "小企业运营",
      "本地营销",
      "现金流与定价",
      "员工与客户管理",
      "网站与数字化",
      "创业问答"
    ],
    "relevance": "高：大量非技术小企业需要低成本建站与内容工具，是 Buildin AI 的潜在终端用户群，但推广必须强约束。",
    "notes": "官方帖摘要反复说明该社区是小企业问答板块；推广应进入每周 Promote Your Business 线程，主 feed 的违规帖可能被移除并伴随临时或永久封禁。",
    "tier": "P0",
    "category": "小企业/经营者",
    "posting_pattern": "以具体经营问题和经验答复为主；周期性推广线程集中承接商家介绍，主 feed 中直接产品帖较少。",
    "user_profile": "小企业主、本地商家、电商经营者、自由职业者、服务业经营者及准备开业的人群。",
    "moderation": "严格",
    "promo_ratio": "观察估计：3%–10%",
    "promo_ratio_note": "观察估计，非严格抽样。依据主版面 Q&A 定位与官方周度推广帖分流机制；主 feed 明显推广较低，若计入每周集中帖则会显著升高。",
    "promo_strategy": "长期回答网站上线、在线获客和效率问题，提供可执行步骤且不主动导流；直接介绍 Buildin AI 时仅进入当周 Promote Your Business 线程，文案简短、说明适用商家和实际收益。",
    "risk": "高：在问答帖中主动推销、使用缩短链接、批量复制评论或伪装成普通用户推荐，可能触发 AutoModerator、删帖或封禁。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/marketing",
    "url": "https://www.reddit.com/r/marketing/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "很高：营销策略、渠道、内容、广告、数据、归因和 martech 讨论广泛，专业从业者与入门提问并存。",
    "atmosphere": "专业但挑剔；从业者擅长识别软广，对真实实验、策略争论和有上下文的问题更认可。",
    "sentiment": "中性偏怀疑：对有证据的营销实践愿意深入讨论，对代理商获客、博客导流、AI 生成内容和工具自荐容忍度很低。",
    "main_topics": [
      "营销策略",
      "广告与媒介",
      "内容与文案",
      "SEO/社媒/邮件",
      "数据与归因",
      "MarTech 与优化"
    ],
    "relevance": "中：适合研究营销人员需求和分享可验证的内容/落地页实验，不适合直接推广 Buildin AI。",
    "notes": "社区公开介绍覆盖营销策略、媒介、数字、社交、搜索、活动、数据、邮件、UX、内容、归因、测试和 martech。公开规则摘要显示对广告、自推广、垃圾内容及 AI 生成内容采取零容忍，并可能永久封禁。",
    "tier": "P2",
    "category": "营销/广告专业",
    "posting_pattern": "策略问答、职业与团队问题、渠道效果讨论、案例争论及行业新闻；低背景求助、调查、app feedback 和自有博客链接容易被移除。",
    "user_profile": "品牌与增长营销人员、代理商从业者、内容/SEO/付费投放专家、分析师、营销负责人及学生。",
    "moderation": "极严格",
    "promo_ratio": "观察估计：1%–5%",
    "promo_ratio_note": "观察估计，非严格抽样。依据公开的零容忍自推广规则及对 app feedback、调查、AI 内容的限制；仅估主 feed 中仍可见的明显或疑似软广。",
    "promo_strategy": "不做产品发布。仅以人工撰写、数据充分且去品牌化的实验复盘参与讨论；如规则存在当期官方主题帖，也须逐次复核后再发。更安全的方式是评论回答并避免主动提及产品。",
    "risk": "极高：产品名、代理商身份导流、自有博客、AI 生成文案、调查或伪装式“你们用什么工具”都可能导致删除或永久封禁。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/GrowthHacking",
    "url": "https://www.reddit.com/r/GrowthHacking/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中：有稳定的增长问题、工具、实验和案例帖，但互动通常低于大型营销/创业社区；数据扎实的案例更易突出。",
    "atmosphere": "战术与实验导向，偏好新方法和可复制步骤；同时存在工具推荐、外链和增长服务带来的推广噪声。",
    "sentiment": "中性偏正向：乐于讨论增长实验，但对无结果证明、门槛内容和纯自推较冷淡。",
    "main_topics": [
      "增长实验",
      "获客渠道",
      "转化率优化",
      "内容与社媒增长",
      "增长工具",
      "创业增长案例"
    ],
    "relevance": "中高：可用 Buildin AI 的落地页/内容实验作为案例，但必须以方法、结果和复盘为核心。",
    "notes": "社区公开描述面向增长实践者和专业人士，鼓励讨论增长营销问题、新实验、工具和创业增长故事。公开规则片段出现“不分享 gated content”“禁止自推广”等限制，因此不能把“讨论工具”理解为可直接投放。",
    "tier": "P1",
    "category": "增长营销",
    "posting_pattern": "渠道实验、增长案例、工具讨论、问题求助和行业新闻；有数字、时间窗、基线与结论的帖子更符合社区预期。",
    "user_profile": "增长营销人员、创业者、产品增长从业者、数字营销顾问及尝试新获客渠道的独立开发者。",
    "moderation": "严格",
    "promo_ratio": "观察估计：10%–20%",
    "promo_ratio_note": "观察估计，非严格抽样。公开新帖与讨论中可见工具/服务相关内容，但规则明确反对无价值自推；区间包含案例中的软性品牌提及，不能视为允许比例。",
    "promo_strategy": "发布完整实验拆解：假设、基线、执行步骤、周期、结果、失败点与可复现模板；若提及 Buildin AI，透明披露并让案例在删除产品名后仍有独立价值，避免 gated lead magnet 和销售 CTA。",
    "risk": "高：直接推广、门槛下载、模糊“增长秘籍”、无数据案例或伪装成经验的导流，可能被移除并损害账号信誉。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/selfhosted",
    "url": "https://www.reddit.com/r/selfhosted/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "高；主题流更新快，周度 New Project Megathread 可稳定获得百余条回复",
    "atmosphere": "技术密集、务实、重视可部署性与透明度；对云端锁定、模糊许可和空泛 AI 营销较警惕",
    "sentiment": "对开源、可自托管、数据可控的工具偏积极；对闭源云端 AI 产品偏谨慎或负面",
    "main_topics": [
      "自托管应用发现与评测",
      "Docker/Compose 与部署",
      "家庭服务器",
      "备份与运维",
      "开源许可",
      "隐私与数据所有权",
      "新项目展示"
    ],
    "relevance": "高：若 Buildin AI 提供自托管、数据导出、隐私说明或开源组件，可直接命中核心需求；纯云端版本相关性明显下降",
    "notes": "社区已把三个月内的新项目集中到周度 megathread，说明主版面正主动压缩新品发布噪声；适合用完整技术材料而非品牌广告切入",
    "tier": "P0",
    "category": "自托管/开源技术",
    "posting_pattern": "高频问答、部署排障、项目展示和架构讨论并存；新品推广主要进入每周 New Project Megathread",
    "user_profile": "自托管爱好者、开发者、系统管理员、家庭服务器玩家及重视数据主权的高级用户",
    "moderation": "严格",
    "promo_ratio": "观察估计：主信息流约 5%–12%；若计入周度 New Project Megathread 内评论，推广内容集中度会显著上升",
    "promo_ratio_note": "非严谨抽样。依据为社区主页/近期检索结果及 2026 年 7–9 月连续周度项目帖；项目帖约有 92–193 条评论，且规则说明新项目应集中发布，故主信息流直推比例应较低。",
    "promo_strategy": "仅在确有自托管能力时进入；优先在周度项目帖披露团队身份，提供仓库、Docker Compose、最低资源占用、数据流向、备份/迁移和许可说明；先回答技术问题，再邀请试用，避免“AI 全能工具”式文案。",
    "risk": "高风险点是闭源或仅 SaaS、标题党、重复发布、没有仓库/部署文档、回避遥测与数据处理问题；可能被移除并引发负面追问。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/privacy",
    "url": "https://www.reddit.com/r/privacy/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "高；隐私新闻、平台政策、工具选择与个人威胁模型讨论持续活跃",
    "atmosphere": "质疑性强、证据导向、反追踪与反数据滥用；对 AI、闭源软件和商业利益相关内容尤其敏感",
    "sentiment": "对能证明最小化收集、端侧处理、可删除/可导出的方案有条件积极；对营销话术和未经证实的隐私承诺偏负面",
    "main_topics": [
      "数字隐私",
      "追踪与数据经纪",
      "隐私工具",
      "威胁模型",
      "平台数据政策",
      "AI 数据使用",
      "法规与新闻"
    ],
    "relevance": "中：只有在 Buildin AI 能提供可核验的隐私架构、数据保留与模型训练说明时才适合；不是通用获客社区",
    "notes": "社区明确强调数字隐私而非一般安全，且将公开数据、闭源等部分话题视为离题；发布前应逐条核对当前规则",
    "tier": "P1",
    "category": "隐私/数据权利",
    "posting_pattern": "新闻链接、隐私争议讨论、求助与工具比较为主；商业产品独立推广少见，评论常追问证据与利益关系",
    "user_profile": "隐私倡导者、技术用户、安全/政策关注者，以及寻求减少平台追踪的普通用户",
    "moderation": "极严格",
    "promo_ratio": "观察估计：约 0%–5% 的可见帖子带明显推广意图",
    "promo_ratio_note": "非严谨抽样。依据为社区定位、搜索结果中可见的版主移除案例，以及对闭源/营利公司讨论边界的长期争议；没有进行可重复的完整信息流计数。",
    "promo_strategy": "不做直接拉新。用透明的隐私技术说明、威胁模型、数据保留/删除流程或开源审计材料参与相关讨论；明确从属关系，并把 Buildin AI 仅作为可选实现例，不夸大“零知识”“不训练”等表述。",
    "risk": "若产品闭源、云端处理不透明、要求敏感权限，或把一般安全/效率话题包装成隐私内容，极易被质疑、举报或删除。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/opensource",
    "url": "https://www.reddit.com/r/opensource/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中高；开源项目、许可证、治理和项目求助持续出现",
    "atmosphere": "开发者导向、重视许可证定义与可验证仓库；欢迎真正开源项目，但反感把社区当链接农场",
    "sentiment": "对解决明确问题、代码可审查且持续维护的项目积极；对 open-core 模糊宣传和高频自推谨慎",
    "main_topics": [
      "开源项目发布",
      "许可证选择",
      "项目治理",
      "贡献者招募",
      "代码托管",
      "可持续商业模式",
      "开源替代品"
    ],
    "relevance": "中高：若 Buildin AI 的核心或关键组件采用 OSI 意义上的开源许可证，适合进行技术发布；否则不宜强行进入",
    "notes": "社区说明允许在一定程度上展示自己的工作，但不希望成为项目、网站或 YouTube 链接农场，并援引低于 10% 自推的建议",
    "tier": "P1",
    "category": "开源生态",
    "posting_pattern": "项目介绍、许可证问答、开发协作和行业讨论混合；项目帖需要有上下文、技术细节和社区价值",
    "user_profile": "开源维护者、贡献者、独立开发者、技术用户和关注许可证/治理的人群",
    "moderation": "中等",
    "promo_ratio": "观察估计：约 10%–20% 为项目展示或带作者利益关系的内容",
    "promo_ratio_note": "非严谨抽样。依据为社区主题天然包含项目发布，同时公开规则片段强调鼓励适度展示、避免链接农场并建议自推低于 10%；区间把非商业项目展示也纳入了广义推广。",
    "promo_strategy": "发布技术复盘而非落地页：说明许可证、仓库、架构、可复现安装、贡献路线和已知限制；披露作者身份，邀请 issue/PR；账号整体保持大量非自推贡献。",
    "risk": "许可证不合格、仓库空壳、只开源客户端、频繁跨版复制或把 SaaS 称作开源，都会迅速损害信誉。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/homelab",
    "url": "https://www.reddit.com/r/homelab/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "高；实验室展示、硬件故障、网络/虚拟化排障和项目帖密集",
    "atmosphere": "友好但技术标准高，重视真实搭建、成本、性能和可复现经验；对无关营销耐受度低",
    "sentiment": "对能在家用硬件稳定运行、资源占用透明的工具偏积极；对纯云端或缺乏实测数据的 AI 产品谨慎",
    "main_topics": [
      "家庭实验室展示",
      "服务器与存储",
      "虚拟化",
      "网络",
      "Kubernetes/容器",
      "硬件采购",
      "故障排查"
    ],
    "relevance": "中高：自托管 AI 工作流、知识库或创作系统若可在 NAS/迷你主机部署，会有明确受众",
    "notes": "官方 wiki 将社区定位为技术人员和系统管理员分享实验室、项目与构建；应把产品放在真实 homelab 场景中展示",
    "tier": "P1",
    "category": "Homelab/基础设施",
    "posting_pattern": "图片化实验室展示、配置清单、故障求助和深度项目复盘；评论常追问功耗、成本、网络拓扑和维护方式",
    "user_profile": "系统管理员、网络/平台工程师、IT 学习者、NAS 与家庭服务器爱好者",
    "moderation": "严格",
    "promo_ratio": "观察估计：约 3%–8% 为明显推广；项目展示更多但多数不是商业推广",
    "promo_ratio_note": "非严谨抽样。依据为公开热榜/新帖片段与规则页；社区允许分享 projects/builds，但商业链接与普通实验室展示难以机械区分，因此仅给区间。",
    "promo_strategy": "以“在何种硬件上如何部署 Buildin AI”为核心，提供拓扑图、Compose/Helm、CPU/RAM/显存占用、离线能力、备份与失败教训；品牌链接置后，并提前向版主确认软件项目展示规则。",
    "risk": "软广伪装成实验室展示、缺乏硬件/性能细节、与 homelab 无关、厂家账号回避身份，均可能被删除或负评。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/degoogle",
    "url": "https://www.reddit.com/r/degoogle/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中高；替代品求助、迁移经验与 Google 政策讨论稳定出现",
    "atmosphere": "使命驱动、重视去中心化与减少 Google 依赖；实用主义和隐私意识并重",
    "sentiment": "对真正不依赖 Google、开源且可迁移的替代品积极；对仅借“去 Google”营销的产品敏感",
    "main_topics": [
      "Google 替代品",
      "账号与数据迁移",
      "去中心化",
      "开源工具",
      "隐私",
      "自托管",
      "Android/搜索/邮箱替代"
    ],
    "relevance": "中高：若 Buildin AI 不依赖 Google 服务并能替代 Google Docs/Drive 相关创作或知识工作流，可形成清晰切入点",
    "notes": "社区有每周 Degoogle Showcase；独立项目推广会被移除并引导到 Showcase，项目需开源、有公开仓库且不得依赖 Google 服务",
    "tier": "P1",
    "category": "去平台化/隐私替代",
    "posting_pattern": "替代品清单、迁移求助、政策讨论和每周项目 Showcase；独立推广帖受限",
    "user_profile": "希望降低 Google 依赖的隐私用户、开源爱好者、自托管用户和 Android 高级用户",
    "moderation": "严格",
    "promo_ratio": "观察估计：主信息流约 2%–6%；推广主要集中在每周 Showcase",
    "promo_ratio_note": "非严谨抽样。依据为近期 Showcase 规则摘要：任何日期可在周帖评论发布，独立项目推广会被移除；未对完整主信息流做统计抽样。",
    "promo_strategy": "进入每周 Showcase，明确公开仓库、许可证、无 Google 依赖证明、数据导出和自托管路径；用“替代哪一段 Google 工作流”的迁移教程切入，不做宽泛 AI 宣传。",
    "risk": "依赖 Google 登录、Analytics、Firebase、Gemini 或 Google Cloud 却未披露，会直接违背社区预期；闭源或伪开源同样风险高。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Substack",
    "url": "https://www.reddit.com/r/Substack/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中高；增长、Notes、推荐网络、付费转化和平台问题讨论持续出现",
    "atmosphere": "创作者互助与增长焦虑并存；愿意交换实操经验，但对泛滥的 newsletter 链接和互关式推广反感",
    "sentiment": "对可落地的写作、分发和订阅增长方法积极；对无上下文自推偏负面",
    "main_topics": [
      "Newsletter 增长",
      "付费订阅",
      "Substack Notes",
      "推荐与交叉推广",
      "写作流程",
      "数据分析",
      "平台功能与故障"
    ],
    "relevance": "高：与独立写作者、newsletter 运营和内容变现高度重合，适合验证 AI 写作辅助、选题、复用与知识管理价值",
    "notes": "社区曾专门发布新的 self-promo 规则，且存在用户公开抱怨自推泛滥；说明推广需求强但容忍度有限",
    "tier": "P0",
    "category": "Newsletter/创作者变现",
    "posting_pattern": "问题求助、增长复盘、平台动态和写作经验为主；newsletter 分享受到专门规则或集中帖约束",
    "user_profile": "独立写作者、记者、newsletter 经营者、付费订阅创作者和准备从零起步的作者",
    "moderation": "严格",
    "promo_ratio": "观察估计：约 8%–18% 的可见内容具有 newsletter/服务推广意图，规则收紧后主信息流比例可能更低",
    "promo_ratio_note": "非严谨抽样。依据为 2024 年版主发布的“New rules on self-promo”和社区对推广噪声的讨论；无法稳定抓取完整新帖列表，故不给精确比例。",
    "promo_strategy": "先发布可独立使用的增长/工作流复盘，例如从选题到多渠道复用的具体流程与前后对比；披露 Buildin AI 身份，链接放末尾，并优先使用允许的自推帖或先发 modmail 确认。",
    "risk": "直接贴 newsletter/产品链接、互订互关、夸大收入增长、批量 AI 内容或冒充普通用户，会触发反感和删除。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/patreon",
    "url": "https://www.reddit.com/r/patreon/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中；以创作者求助、平台政策、账号问题和变现经验为主，单帖互动通常从少量到数十条回复",
    "atmosphere": "问题解决导向，创作者之间分享经验；对把社区当作 Patreon 页面广告位的做法不友好",
    "sentiment": "对能节省运营时间、改善会员交付的工具有条件积极；对直接拉会员或泛营销谨慎",
    "main_topics": [
      "会员层级设计",
      "定价",
      "获客与留存",
      "平台规则",
      "付款与账号问题",
      "内容交付",
      "NSFW/合规"
    ],
    "relevance": "高：用户本身就是内容变现创作者，可切入会员内容规划、复用、运营分析和交付效率",
    "notes": "社区被描述为非官方、志愿者运营的 Patreon 创作者技巧与问答社区；检索结果显示常见发帖是询问如何推广，而非允许直接推广 Patreon 页面",
    "tier": "P0",
    "category": "会员制创作者变现",
    "posting_pattern": "求助帖与经验问答占主导，常见主题包括平台审核、会员运营和推广渠道；明显拉会员帖较少",
    "user_profile": "Patreon 创作者、准备开通会员制的内容生产者，以及处理付款/审核问题的经营者",
    "moderation": "中等",
    "promo_ratio": "观察估计：约 3%–10% 为明显自推或引流内容",
    "promo_ratio_note": "非严谨抽样。依据为搜索可见帖子主要集中在“如何推广”“规则/账号问题”和创作者互助，且讨论中明确提到多数社区限制自推；未完成完整信息流计数。",
    "promo_strategy": "发布不依赖产品链接也有价值的会员运营模板、内容日历或留存复盘；在回答具体问题时透明说明 Buildin AI，并将产品作为多个可选方案之一，不推广单个 Patreon 页面。",
    "risk": "直接招揽付费会员、频繁落地页链接、对平台政策给出不准确建议，或涉及 NSFW 合规却缺少谨慎措辞，都会造成删除和声誉风险。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Blogging",
    "url": "https://www.reddit.com/r/Blogging/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中高；SEO、流量、写作、博客平台和收入问题持续出现",
    "atmosphere": "新手与经营型博主混合，偏实操和互助；对低质量 AI 内容、链接倾倒和伪装反馈请求警惕",
    "sentiment": "对真实案例、可复现流程和编辑效率工具偏积极；对承诺快速流量/收入的工具负面",
    "main_topics": [
      "博客起步",
      "SEO",
      "内容策略",
      "流量增长",
      "广告与联盟营销",
      "写作工具",
      "网站反馈"
    ],
    "relevance": "高：Buildin AI 可对应选题研究、编辑流程、内容复用和知识资产管理，但需避免被视为 AI 批量内容工具",
    "notes": "社区反馈帖要求网站至少有 5 篇内容、提出具体问题，并明确警告借反馈帖自推会被迅速封禁",
    "tier": "P0",
    "category": "博客/内容增长",
    "posting_pattern": "问答与经验帖为主，站点反馈集中到专门线程；裸链接和单篇文章反馈受到限制",
    "user_profile": "新手博主、SEO 从业者、联盟营销者、独立站经营者和内容编辑",
    "moderation": "极严格",
    "promo_ratio": "观察估计：主信息流约 2%–6%；反馈集中帖中带站点链接的比例更高但并不等同允许推广",
    "promo_ratio_note": "非严谨抽样。依据为社区首页/反馈帖规则摘要明确限制链接、要求具体反馈目标，并警告滥用自推会被封禁；未对新帖做完整抽样。",
    "promo_strategy": "用长文本案例拆解真实博客工作流、编辑质检或内容复用方法；若请求产品反馈，严格进入指定线程、满足站点条件并提出具体问题；先贡献评论，避免直接贴首页。",
    "risk": "把反馈线程当广告位、推广 AI 批量文章、承诺 SEO 捷径、重复贴博客链接或无披露联盟关系，封控风险很高。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/NewTubers",
    "url": "https://www.reddit.com/r/NewTubers/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（第三方称约 80 万+，但未获 Reddit 官方页面可靠确认）",
    "activity": "高；小型 YouTube 创作者围绕选题、缩略图、留存、算法和频道诊断高频交流",
    "atmosphere": "强互助、成长导向，但重复问题和自推冲动都很高；强调批评、合作与给出具体反馈",
    "sentiment": "对基于真实频道数据的工作流和经验复盘积极；对视频链接倾倒、sub4sub 和虚假增长负面",
    "main_topics": [
      "YouTube 起步",
      "选题与脚本",
      "缩略图/标题",
      "观众留存",
      "频道分析",
      "内容制作",
      "创作者倦怠"
    ],
    "relevance": "中高：适合验证脚本策划、研究整理和多平台复用能力，但产品宣传必须服从教育与互助语境",
    "notes": "官方规则页将其定位为帮助小型创作者通过资源、批评和合作来建立内容事业；社区经验强调内容应先解决受众问题，再自然附加链接",
    "tier": "P1",
    "category": "视频创作者成长",
    "posting_pattern": "问题求助、频道成长经验、数据诊断和反馈讨论为主；直接视频推广通常不受欢迎或被导向指定机制",
    "user_profile": "小型/新手 YouTuber、Twitch 主播、兼职创作者及寻求频道增长方法的人群",
    "moderation": "严格",
    "promo_ratio": "观察估计：主信息流约 2%–7% 为明显自推；寻求反馈的准推广内容另有较高占比",
    "promo_ratio_note": "非严谨抽样。依据为规则定位、多个自推讨论和外部汇总对“多数 YouTube 社区禁止直接视频推广”的提醒；未把所有反馈帖都计作推广。",
    "promo_strategy": "提供可执行的脚本/选题/复盘模板，以匿名化或自有案例展示方法；在获准的反馈场景披露产品身份，先给别人具体反馈，绝不做 sub4sub 或冷贴视频。",
    "risk": "直接发频道/视频、低投入 AI 内容、sub4sub、伪造数据或把普通问答导向付费产品，容易删除并损害品牌。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/ContentCreators",
    "url": "https://www.reddit.com/r/ContentCreators/",
    "product": "Buildin AI",
    "members": null,
    "members_display": "未可靠核验（Reddit 页面抓取受限，未采用第三方估值）",
    "activity": "中；跨平台创作者求助、工具讨论、合作与反馈需求并存",
    "atmosphere": "广谱、偏新手、互助与自推需求都强；对裸链接、增长捷径和互关行为反感",
    "sentiment": "对具体创作方法、工具比较和建设性反馈积极；对广告式帖文与 engagement pod 负面",
    "main_topics": [
      "跨平台内容创作",
      "创作者工具",
      "增长",
      "变现",
      "内容反馈",
      "合作",
      "工作流"
    ],
    "relevance": "高：覆盖多类型创作者，可测试 Buildin AI 的泛创作与跨平台复用叙事，但用户意图较分散",
    "notes": "可检索规则汇总显示主信息流禁止裸自推/链接倾倒，推广与反馈应进入置顶线程，并强调 give-to-get；该依据非 Reddit 官方页面，发布前必须复核实时规则",
    "tier": "P0",
    "category": "泛内容创作者",
    "posting_pattern": "工具/增长问答、合作请求和作品反馈混合；自推需求被集中到置顶推广或反馈线程",
    "user_profile": "YouTube、短视频、播客、社媒和独立内容创作者，整体以早期与成长阶段为主",
    "moderation": "严格",
    "promo_ratio": "观察估计：主信息流约 5%–12%；置顶自推/反馈线程内显著更高",
    "promo_ratio_note": "非严谨抽样。依据为可检索的 2026 规则汇总所述“禁止主信息流裸链接、使用置顶推广/反馈帖”；由于未获得官方规则全文，区间置信度低于其他社区。",
    "promo_strategy": "只在置顶允许的线程发布链接；主信息流发跨平台工作流、创作复盘或工具选型讨论，披露 Buildin AI 关系并先参与 give-to-get 反馈；避免泛泛介绍产品。",
    "risk": "规则证据来自非官方汇总且可能变动；裸链接、sub4sub/follow-for-follow、互动群或冷启动广告有较高移除风险，发帖前应再查置顶帖和 modmail。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Notion",
    "url": "https://www.reddit.com/r/Notion/",
    "product": "Notion",
    "members": null,
    "members_display": "约46.9万（第三方统计，未独立核验）",
    "activity": "高；最新帖流在同日持续更新，问题求助、模板/自动化与故障讨论密集",
    "atmosphere": "大型、实用主义、入门用户很多；既有互助，也有对价格、AI、账号与产品变更的抱怨",
    "sentiment": "中性偏正，夹杂对商业化和稳定性的明显质疑",
    "main_topics": [
      "数据库与模板",
      "自动化与集成",
      "工作流展示",
      "故障排查",
      "价格与账户",
      "Notion 替代品"
    ],
    "relevance": "高：用户正在主动寻找知识库、数据库、模板和自动化方案，但竞品心智很强",
    "notes": "社区自述为 community-run。推广集中到指定周常帖；主版适合需求洞察和高质量答疑，不适合直接投放产品帖。",
    "tier": "P1",
    "category": "产品型社区 / 协作工作区与知识管理",
    "posting_pattern": "高频问答为主，截图求助、模板展示、自动化案例和迁移讨论常见；新帖更新可达小时级",
    "user_profile": "学生、知识工作者、自由职业者、团队管理员、模板创作者及自动化重度用户",
    "moderation": "严格",
    "promo_ratio": "观察估计：5%–15%",
    "promo_ratio_note": "基于 2026-09-09 可见最新帖流的标题与正文快速观察；包含模板、教程、集成和自动化展示等品牌/创作者导向内容。未做随机抽样，且被删帖不可见，因此仅为观察估计。",
    "promo_strategy": "先连续参与数据库、迁移和自动化求助；以可复用教程或对比实验切入，披露与 Buildin AI 的关系；如需直接展示产品，仅使用允许的周常推广帖或先发 modmail。",
    "risk": "高：大型社区反营销敏感，模板售卖、外链导流、重复跨版发布和伪装用户口碑容易被删或封禁。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/ObsidianMD",
    "url": "https://www.reddit.com/r/ObsidianMD/",
    "product": "Obsidian",
    "members": null,
    "members_display": "约34.4万（第三方统计，未独立核验）",
    "activity": "高；最新 25 条通常覆盖很短时间窗，技术求助与工作流讨论连续出现",
    "atmosphere": "技术型、DIY、重视本地文件与长期可控性；乐于分享插件和复杂工作流，也会警惕过度工程化",
    "sentiment": "整体正向但批判性强；对插件依赖、同步成本和学习曲线讨论充分",
    "main_topics": [
      "插件与主题",
      "Vault 结构",
      "Markdown 与本地优先",
      "同步与移动端",
      "Web Clipper",
      "Notion 对比与迁移"
    ],
    "relevance": "高：与个人知识库和 AI 辅助整理高度重叠，适合验证本地优先、数据可迁移和复杂工作流需求",
    "notes": "社区近期有管理员明确打击“首帖即推广应用”，说明对新账号、批量 AI 营销和纯推广账户高度敏感。",
    "tier": "P1",
    "category": "产品型社区 / 本地优先知识管理",
    "posting_pattern": "高频长文求助、配置展示、插件推荐、同步排障和工具对比；评论往往偏技术细节",
    "user_profile": "开发者、研究者、学生、写作者、隐私敏感用户和 PKM 高阶玩家",
    "moderation": "严格",
    "promo_ratio": "观察估计：8%–18%",
    "promo_ratio_note": "依据最新帖流及第三方主题分析，插件、主题、教程和个人项目可见度较高；但管理员会清理首帖推广和批量营销。未获得完整删帖记录，区间仅为观察估计。",
    "promo_strategy": "用技术深度换信任：先回答迁移、Markdown、数据所有权与 AI 工作流问题；发布时提供完整方法、样例与局限，公开身份，不用“我做了一个更好的 Obsidian”式标题。",
    "risk": "高：用户重视数据所有权且反感营销包装；若 Buildin AI 的云端、导出和锁定策略交代不清，容易引发负面比较。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/productivity",
    "url": "https://www.reddit.com/r/productivity/",
    "product": "通用生产力方法与工具",
    "members": null,
    "members_display": "约320万（第三方估算，未独立核验）",
    "activity": "极高；观察到最新 25 帖约覆盖一天半，日内持续有新问题",
    "atmosphere": "大众化、问题驱动、互助与情绪支持并存；更关注拖延、专注和生活管理，而非单一软件",
    "sentiment": "中性偏支持，但对泛泛鸡汤、AI 生成内容和应用营销耐心很低",
    "main_topics": [
      "拖延与专注",
      "时间管理",
      "习惯与精力",
      "学习效率",
      "应用推荐",
      "工作生活平衡"
    ],
    "relevance": "高：受众规模和需求面广，适合捕捉高意图场景；但直接推广空间极小",
    "notes": "规则明确禁止任何形式的自我推广、招揽、调查、推荐码和私信广告，并限制孤立链接、低质量及 AI 生成内容。",
    "tier": "P0",
    "category": "主题型社区 / 综合生产力",
    "posting_pattern": "大量个人困境与建议请求，标题口语化；应用推荐帖存在但通常要求真实体验和上下文",
    "user_profile": "学生、远程工作者、职场人、注意力/拖延困扰者及寻找轻量工具的大众用户",
    "moderation": "极严格",
    "promo_ratio": "观察估计：0%–3%",
    "promo_ratio_note": "最新 25 帖中主要是求助和讨论，未见明显产品方直推；结合规则对自我推广的全面禁止，主版可见推广比例预计极低。该值为可见帖观察估计，不包含已移除内容。",
    "promo_strategy": "不要发产品帖、调查帖、推荐码或主动私信。只做非推广性的高质量问题回答和需求语言研究；若自然被问及工具，也应先给中立选项并谨慎披露身份。",
    "risk": "极高：产品提及、AI 生成痕迹、SEO 式长文、无上下文链接均可能触发删除或封禁。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/PKMS",
    "url": "https://www.reddit.com/r/PKMS/",
    "product": "个人知识管理系统（跨工具）",
    "members": null,
    "members_display": "约5.05万（Reddit 搜索结果快照，未实时复核）",
    "activity": "中等；最新帖并非持续小时级更新，但仍有稳定的迁移、选型和方法论讨论",
    "atmosphere": "工具无关、系统思考浓、愿意比较多款产品；对隐性推广和重复推销已有明显疲劳",
    "sentiment": "审慎中性；鼓励探索，但会追问数据所有权、成本、学习曲线和长期可用性",
    "main_topics": [
      "PKM 方法论",
      "工具选型与迁移",
      "第二大脑",
      "Zettelkasten",
      "本地优先",
      "AI 与知识图谱"
    ],
    "relevance": "极高：用户处于主动选型和迁移阶段，是 Buildin AI 获取产品洞察与高意向反馈的核心社区",
    "notes": "主版推广帖会被移除并引导至月度 Self Promotion 集中帖；社区成员还要求覆盖隐性推广。",
    "tier": "P0",
    "category": "主题型社区 / 个人知识管理",
    "posting_pattern": "中长篇选型求助、现有系统复盘、跨产品比较和方法论讨论；月度集中推广帖承接产品发布",
    "user_profile": "PKM 爱好者、研究者、写作者、开发者和希望从 Notion/Obsidian 等迁移的高意向用户",
    "moderation": "严格",
    "promo_ratio": "观察估计：主版 0%–5%；月度推广帖内接近 100%",
    "promo_ratio_note": "主版规则与月度 Self Promotion 帖明确分流；最新帖流以迁移和方法讨论为主。没有完整随机样本和删帖数据，因此为观察估计，并将主版与集中帖分开表述。",
    "promo_strategy": "主版只做深度答疑、迁移清单和方法对比；产品介绍集中投放月度推广帖，明确创作者身份、具体用例、数据策略和反馈诉求。",
    "risk": "高：将软文伪装成“求推荐”或在评论中隐性导流，容易被用户举报并损害品牌信誉。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/PersonalKnowledgeMgmt",
    "url": "https://www.reddit.com/r/PersonalKnowledgeMgmt/",
    "product": "个人知识管理（方法与实践）",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "低到中等；搜索可见度和实时帖流均弱于 r/PKMS",
    "atmosphere": "偏学习者与方法论交流，强调 sense-making、写作、智能笔记与终身学习",
    "sentiment": "温和正向、探索型；对工具保持开放，但内容价值高于产品曝光",
    "main_topics": [
      "知识建构",
      "学习与写作",
      "智能笔记",
      "第二大脑",
      "工作流",
      "工具与文章分享"
    ],
    "relevance": "高：主题与 Buildin AI 高度吻合，适合进行教育型内容和用户访谈招募，但规模与活跃度有限",
    "notes": "未可靠取得该社区的独立推广规则或稳定最新帖样本；推广判断以社区简介、可见讨论和 Reddit 通用反垃圾规范为依据。",
    "tier": "P0",
    "category": "主题型社区 / PKM 方法与学习",
    "posting_pattern": "较低频的文章、方法、工作流和工具讨论；更适合长尾内容而非追求即时曝光",
    "user_profile": "终身学习者、写作者、研究者、教育从业者和第二大脑实践者",
    "moderation": "中等",
    "promo_ratio": "观察估计：5%–15%",
    "promo_ratio_note": "仅依据搜索可见帖子类型和社区定位进行低置信度估计，未能稳定获取完整最新帖流，也无法观察已删内容；不得作为统计值使用。",
    "promo_strategy": "以 PKM 方法论、案例复盘和可复制框架为主，正文先完整交付价值；如提及 Buildin AI，需透明披露并把链接放在次要位置，最好先向版主确认。",
    "risk": "中等：主要风险是社区体量较小、触达有限，以及工具软文削弱方法论可信度。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/logseq",
    "url": "https://www.reddit.com/r/logseq/",
    "product": "Logseq",
    "members": null,
    "members_display": "约4.5万（Reddit 页面搜索快照，未实时复核）",
    "activity": "中低；有持续技术求助，但讨论密度低于 Notion 和 Obsidian",
    "atmosphere": "开源、本地优先、技术导向；熟悉大纲、块引用和插件的高阶用户较多",
    "sentiment": "混合；认同产品理念，同时关注开发节奏、数据库版本、插件维护与可靠性",
    "main_topics": [
      "块级大纲",
      "本地优先",
      "插件与查询",
      "同步与备份",
      "Logseq DB",
      "迁移与长期维护"
    ],
    "relevance": "中高：适合验证双链、块级知识和本地数据需求，但受众较窄且对产品真实性要求高",
    "notes": "社区页面称可分享与 PKM 相关的自有应用，但禁止更新日志式和重复发布；重复行为可能被视为垃圾内容并封禁。",
    "tier": "P1",
    "category": "产品型社区 / 本地优先大纲知识库",
    "posting_pattern": "技术排障、插件技巧、DB 版本讨论和工作流提问为主；发帖频率中低，长尾回复价值较高",
    "user_profile": "开发者、研究人员、开源软件用户、重度大纲笔记和本地优先用户",
    "moderation": "中等",
    "promo_ratio": "观察估计：5%–12%",
    "promo_ratio_note": "结合社区公开说明允许相关自有应用、但禁止 changelog 和重复帖，以及可见帖子类型估计；未完成严格随机抽样。",
    "promo_strategy": "可发布与 Logseq 互补的技术内容、开源集成或迁移工具，但要一次性说明价值，避免连续更新帖；强调数据格式、导入导出和本地控制，并积极回答技术问题。",
    "risk": "中高：重复发布会被视为 spam；若只宣传云端 AI 而不解释数据所有权和互操作性，容易被排斥。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Anytype",
    "url": "https://www.reddit.com/r/Anytype/",
    "product": "Anytype",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中等；最新 25 帖约覆盖一个月，通常每天零到数帖",
    "atmosphere": "隐私与数字主权导向，技术问题多，产品团队可见；用户愿意直白表达挫败感",
    "sentiment": "中性偏谨慎；看好本地优先理念，但对移动端、同步、备份和可用性批评较多",
    "main_topics": [
      "数字主权",
      "本地与自托管",
      "同步和备份",
      "对象与集合",
      "移动端",
      "功能请求"
    ],
    "relevance": "中高：与知识对象、AI 和数据自主方向相关，可用于研究隐私敏感型早期用户",
    "notes": "规则明确禁止自我推广，多次违规可永久封禁；官方/团队公告和社区活动本身仍会出现。",
    "tier": "P1",
    "category": "产品型社区 / 隐私与对象化知识管理",
    "posting_pattern": "低到中频的故障求助、功能请求、同步/备份问题、使用案例和团队公告",
    "user_profile": "隐私敏感用户、自托管爱好者、开发者、早期采用者和从 Notion/Obsidian 迁移者",
    "moderation": "严格",
    "promo_ratio": "观察估计：4%–10%",
    "promo_ratio_note": "最新 25 帖中可见少量团队活动、开源集成或自制项目，主体仍为求助和功能讨论；规则禁止自我推广。估计不包含已删除内容。",
    "promo_strategy": "不要直接宣传。优先做与隐私、同步、备份、数据可迁移有关的中立答疑；任何品牌提及都应取得版主同意、充分披露并避免导流式外链。",
    "risk": "高：自我推广规则明确且可永久封禁；云端 AI、数据收集和锁定风险会受到放大审视。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/Capacities",
    "url": "https://www.reddit.com/r/capacitiesapp/",
    "product": "Capacities",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中等；实际活跃社区 r/capacitiesapp 的最新 25 帖约覆盖四周，近期出现同日多帖",
    "atmosphere": "产品共创感较强，围绕对象化 PKM、模板和新功能交流；对性能、丢文件、平台差异和付费功能也很直接",
    "sentiment": "混合偏正；认可对象化思路和更新速度，但稳定性、价格与端侧一致性会引发负面反馈",
    "main_topics": [
      "对象化笔记",
      "Daily Note",
      "模板",
      "API 与集成",
      "移动端",
      "稳定性与数据安全"
    ],
    "relevance": "高：用户与 Buildin AI 的目标人群高度重叠，适合做对象化知识、AI 与跨工具工作流研究",
    "notes": "用户给出的 r/Capacities 未发现稳定可核验的活跃社区页面；调研采用实际活跃的 r/capacitiesapp，并在 URL 中显式纠正。推广规则未可靠获取。",
    "tier": "P1",
    "category": "产品型社区 / 对象化个人知识管理",
    "posting_pattern": "中频产品求助、模板/工作流展示、更新讨论、第三方集成和竞品迁移；偶有重复交叉发布",
    "user_profile": "PKM 进阶用户、创作者、学生、知识工作者、API/自动化爱好者和竞品迁移用户",
    "moderation": "中等",
    "promo_ratio": "观察估计：8%–18%",
    "promo_ratio_note": "对 r/capacitiesapp 最新 25 帖标题观察到官方更新、插件/快捕工具和个人项目展示，但大多数仍为使用问题。未核得完整社区规则及删帖记录，故仅为观察估计。",
    "promo_strategy": "以“如何完成某个 Capacities/PKM 工作流”的教程或互操作方案切入，披露产品关系；不要碰瓷式比较，先在评论解决问题，再询问版主是否可发完整案例。",
    "risk": "中高：社区名称存在歧义；在竞品产品社区直接推广替代品容易引发反感，重复跨发和缺乏披露尤其危险。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/codaio",
    "url": "https://www.reddit.com/r/codaio/",
    "product": "Coda / Superhuman Docs",
    "members": null,
    "members_display": "约3,000（第三方统计，2026-09-07 更新，未独立核验）",
    "activity": "低；最新 25 帖约覆盖两个多月，间隔可达数日",
    "atmosphere": "小型实务社区，自动化、表格和 Pack 用户集中；近期因更名、计费、登录和移动端问题而情绪偏负",
    "sentiment": "负向偏混合；老用户对 Coda 品牌和工作流仍有黏性，但对 Superhuman 更名与产品体验不满明显",
    "main_topics": [
      "表格与自动化",
      "Packs",
      "表单",
      "Notion 迁移",
      "Superhuman 更名",
      "计费与移动端"
    ],
    "relevance": "中等：用户具备复杂工作流和数据库需求，但社区规模小、当前负面议题集中",
    "notes": "社区页面已将产品描述更新为 Coda 更名为 Superhuman Docs；最新帖流中出现模板、Pack 和测试招募，但未核得明确的本版推广细则。",
    "tier": "P2",
    "category": "产品型社区 / 文档数据库与自动化",
    "posting_pattern": "低频深度求助、Pack/模板发布、迁移讨论和产品抱怨；单帖曝光周期可能较长但总流量有限",
    "user_profile": "运营与项目管理人员、无代码构建者、表格/数据库重度用户、自动化顾问和小团队管理员",
    "moderation": "中等",
    "promo_ratio": "观察估计：10%–20%",
    "promo_ratio_note": "最新 25 帖中可见 Pack 发布、模板、测试招募和产品更新，比例高于大型泛社区；样本仅为最近可见帖，未对作者关系逐一核验，故为观察估计。",
    "promo_strategy": "发布面向具体业务流程的迁移指南、模板或对比案例，先贡献可直接复用的步骤；披露身份，并把重点放在解决 Coda/Superhuman 用户痛点，而非泛化品牌曝光。",
    "risk": "中等：社区小导致转化上限有限；趁更名争议做攻击性竞品营销会被视为机会主义，也可能激化负面评论。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/CraftDocs",
    "url": "https://www.reddit.com/r/CraftDocs/",
    "product": "Craft",
    "members": null,
    "members_display": "无法可靠核验",
    "activity": "中高；最新 25 帖约覆盖十天，更新密度稳定",
    "atmosphere": "设计与体验导向、用户互助明显，官方人员参与；对 Apple 生态、排版和跨端体验关注度高",
    "sentiment": "中性偏正；新版本会获积极反馈，但 PDF、同步、格式和平台差异问题也很集中",
    "main_topics": [
      "写作与排版",
      "PDF 导出",
      "Collections",
      "Apple 生态",
      "跨端同步",
      "版本更新与集成"
    ],
    "relevance": "中高：适合研究创作者、写作者和审美敏感知识工作者，但直接竞品推广需非常克制",
    "notes": "社区自述为 Official Craft Docs subreddit；可见官方互动和用户反馈。未可靠获取独立自我推广规则。",
    "tier": "P1",
    "category": "产品型社区 / 写作与文档知识管理",
    "posting_pattern": "中高频功能问答、Bug 报告、版本反馈、写作案例和少量第三方集成展示",
    "user_profile": "Apple 生态用户、写作者、设计师、内容创作者、学生与注重文档美观的知识工作者",
    "moderation": "中等",
    "promo_ratio": "观察估计：4%–10%",
    "promo_ratio_note": "最新 25 帖主要为产品问题与版本反馈，仅少量自建应用/集成展示；未获得完整规则和删帖记录，因此是观察估计。",
    "promo_strategy": "围绕写作、出版、PDF、跨设备和知识整理提供高质量案例；若比较 Buildin AI，应尊重 Craft 优势、公开身份并先征得版主同意，优先评论答疑而非独立推广帖。",
    "risk": "中高：官方产品社区对替代品营销天然敏感；粗糙视觉、泛 AI 文案或借 Bug 贴导流会伤害品牌。",
    "source_checked_at": "2026-09-09"
  },
  {
    "name": "r/tana_inc",
    "url": "https://www.reddit.com/r/tana_inc/",
    "product": "Tana",
    "members": null,
    "members_display": "待确认（未重新核验）",
    "activity": "低",
    "atmosphere": "积极，power user 向，supertag 爱好者",
    "sentiment": "positive",
    "main_topics": [
      "supertag 设计",
      "工作流搭建",
      "AI 功能",
      "命令面板",
      "模板分享"
    ],
    "relevance": "低 - 间接竞品，付费 power user 向",
    "notes": "沿用 index.html 原有 reddit-data：事实上 power user 专用工具；付费门槛较高；用户群小但极度忠诚；学习曲线陡峭。该条未重新核验，社区状态、规则与活跃度可能已变化。",
    "tier": "P1",
    "category": "产品型社区 / 结构化知识管理",
    "posting_pattern": "原记录仅表明以 supertag、工作流、AI 功能、命令面板和模板分享为主；未重新核验发帖频率、固定栏目或推广入口。",
    "user_profile": "Tana power user、结构化笔记与 PKM 高阶用户、工作流搭建者；画像由原记录概括，未重新核验。",
    "moderation": "未知（未重新核验）",
    "promo_ratio": "观察估计：未知（未重新核验）",
    "promo_ratio_note": "未进行新的信息流抽样或规则核验，无法给出可信推广比例；不得将“未知”理解为允许推广。",
    "promo_strategy": "暂不直接推广；发帖前重新核对实时版规、置顶帖和社区活跃度。若允许，优先以 Tana 工作流互操作案例切入并透明披露关系。",
    "risk": "原始资料陈旧且未重新核验；社区规模、活跃度、推广规则和用户态度可能变化，直接投放存在误判与竞品社区反感风险。",
    "source_checked_at": "未重新核验（沿用 index.html 原始记录；整理于 2026-09-09）"
  },
  {
    "name": "Buildin AI（无独立社区）",
    "url": "https://www.reddit.com/search/?q=buildin.ai",
    "product": "Buildin AI",
    "members": 0,
    "members_display": "无（未重新核验）",
    "activity": "无",
    "atmosphere": "无社区存在",
    "sentiment": "unknown",
    "main_topics": [],
    "relevance": "自身 - Reddit 声量极弱，需从零建设",
    "notes": "沿用 index.html 原有 reddit-data：搜索 buildin.ai / buildinai 几乎无相关讨论；无官方 subreddit；与 Product Hunt 0 评价、无主流媒体报道的结论一致；Reddit 是 Buildin 市场声量的重大空白。该结论未重新核验。",
    "tier": "P0",
    "category": "品牌自身 / 无独立社区",
    "posting_pattern": "无独立社区，因此不存在可核验的社区发帖模式；应在相关第三方社区按各自规则参与。",
    "user_profile": "无独立社区，无法定义稳定成员画像；潜在受众需参考目标 PKM、AI、SaaS 与创作者社区。",
    "moderation": "不适用（无独立社区）",
    "promo_ratio": "不适用（无独立社区）",
    "promo_ratio_note": "没有独立 subreddit，因而不存在可计算的社区推广帖比例；原始 Reddit 搜索声量结论未重新核验。",
    "promo_strategy": "不以不存在的自有社区作为投放渠道；优先在匹配的第三方社区提供高价值内容、透明披露身份，并逐社区复核规则。是否创建官方社区应在验证持续讨论需求后决定。",
    "risk": "搜索结果与品牌声量未重新核验；把搜索页当作社区、跨社区重复推广或过早建立无人运营的官方社区，可能造成数据误读与品牌风险。",
    "source_checked_at": "未重新核验（沿用 index.html 原始记录；整理于 2026-09-09）"
  }
];
